baseurl = "http://juangonzalez.com.es"
languageCode = "es-es"
DefaultContentLanguage = "es"
title = "Línea de Comandos"
theme = "hugo-steam-theme"
disqusShortname = ""
# Enable Google Analytics be inserting your tracking code
googleAnalytics = ""
# Number of posts per page
paginate = 5

[params]
	title = "Línea de Comandos"
	subtitle = "Un blog sobre el uso y disfrute de la línea de comandos"
	copyright = "Released under the MIT license."

	# You can choose between green, orange, red and blue.
	themecolor = "orange"

	# Link custom assets relative to /static
	favicon   = "favicon.ico"
	customCSS = []
	customJS  = []

	# To provide some metadata for search engines and the about section in the footer
	# feel free to add a few information about you and your website.
	name = "Juan González"
	bio = "administrador de sistemas"
	description = "Blog sobre el uso y disfrute de la línea de comandos"
	
	# Link your social networks (optional)
	location = ""
	twitter = "juangnzalez"
	linkedin = ""
	googleplus = ""
	facebook = ""
	instagram = ""
	github = "juangnzalez"
	gitlab = ""
	bitbucket = ""

	# Customize or translate the strings
	keepReadingStr = "seguir leyendo"
	backtotopStr = "subir"
	shareStr = "compartir"
	pageNotFoundTitle = "404 - upsss"
